### ISSUE TITLE
Updating the charm icon

### ISSUE THREAD

**Issue by kwm14** [elastisys/layer-charmscaler#1]
Hi,

The design team at Canonical would like to update charm icons to fit within the new circular format, as displayed in the current GUI.

This will improve how charms are displayed in the store, search results and on charm details pages.

I've attached a new version of the charm icon. If you're happy with this change, please could you update the icon and let us know when it's done.

[charmscaler.svg.zip](https://github.com/elastisys/layer-charmscaler/files/1172886/charmscaler.svg.zip)

Thanks

**Comment by simonklb** [comment]
Thanks, the icon looks great!

I've updated it here https://github.com/elastisys/layer-charmscaler-base/commit/164d163b4104cc47dcb1a32019509ba3f61d91eb

I'm wating for a patch to the charm.docker repo to land before I can request a charm-review and get the new charm revision promulgated but it's pushed to the edge channel: https://jujucharms.com/charmscaler/3
